"""Add technique_preferences to users

Revision ID: 89535f5ad61b
Revises: 
Create Date: 2025-06-25 22:43:00.677576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89535f5ad61b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technique_preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('technique_preferences')

    # ### end Alembic commands ###
